In [1]:
#!pip install mlxtend

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Data preprocessing

In [3]:
dataset = pd.read_csv('Market_Basket_Optimisation2.csv', header = None)
transactions = []
for i in range(0, 7501):
  transactions.append([str(dataset.values[i,j]) for j in range(0, 20)])

# One-hot encoding the list with TransactionEncoder, from mlxtend

In [4]:
from mlxtend.preprocessing import TransactionEncoder

In [5]:
my_transactionencoder = TransactionEncoder()
my_transactionencoder.fit(transactions)

# transform the list of transactions True or False tuples into an array 
encoded_transactions = my_transactionencoder.transform(transactions)

# convert the array of encoded transactions into a dataframe
encoded_transactions_df = pd.DataFrame(encoded_transactions, columns=my_transactionencoder.columns_)
encoded_transactions_df

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,True,True,False,True,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7500,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

# Setting minimum support

In [6]:
min_support = 7/len(transactions) 

from mlxtend.frequent_patterns.fpgrowth import fpgrowth
frequent_itemsets = fpgrowth(encoded_transactions_df, min_support=min_support, use_colnames = True)

frequent_itemsets

        support                                  itemsets
0      0.238368                           (mineral water)
1      0.132116                               (green tea)
2      0.076523                          (low fat yogurt)
3      0.071457                                  (shrimp)
4      0.065858                               (olive oil)
...         ...                                       ...
16741  0.000933  (oatmeal, nan, mineral water, chocolate)
16742  0.001067               (oatmeal, nan, ground beef)
16743  0.001067                 (oatmeal, nan, green tea)
16744  0.001067                 (oatmeal, nan, spaghetti)
16745  0.000933                              (nan, cream)

[16746 rows x 2 columns]

# Setting threshold of association rules for analysis

In [7]:
from mlxtend.frequent_patterns import association_rules

association_rules(frequent_itemsets, metric="lift", min_threshold=6.0)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(low fat yogurt, spaghetti, french fries)","(eggs, milk)",0.003600,0.030796,0.000933,0.259259,8.418631,0.000822,1.308426
1,"(eggs, low fat yogurt, spaghetti)","(milk, french fries)",0.003733,0.023730,0.000933,0.250000,10.535112,0.000845,1.301693
2,"(low fat yogurt, milk, french fries)","(eggs, spaghetti)",0.003333,0.036528,0.000933,0.280000,7.665255,0.000811,1.338155
3,"(eggs, low fat yogurt, french fries)","(milk, spaghetti)",0.003466,0.035462,0.000933,0.269231,7.592105,0.000810,1.319894
4,"(eggs, low fat yogurt, milk)","(spaghetti, french fries)",0.003733,0.027596,0.000933,0.250000,9.059179,0.000830,1.296538
...,...,...,...,...,...,...,...,...,...
9435,"(eggs, burger sauce)","(nan, chicken)",0.001600,0.059992,0.000933,0.583333,9.723519,0.000837,2.256019
9436,"(nan, chicken)","(eggs, burger sauce)",0.059992,0.001600,0.000933,0.015556,9.723519,0.000837,1.014176
9437,"(nan, burger sauce)","(eggs, chicken)",0.005866,0.014398,0.000933,0.159091,11.049453,0.000849,1.172067
9438,(chicken),"(eggs, nan, burger sauce)",0.059992,0.001600,0.000933,0.015556,9.723519,0.000837,1.014176
9439,(burger sauce),"(eggs, nan, chicken)",0.005866,0.014398,0.000933,0.159091,11.049453,0.000849,1.172067